# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpx < Formula
  desc "Run any executable inside container on your machine"
  homepage "https://github.com/dpx/dpx"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dpx/dpx/releases/download/v0.1.2/dpx_0.1.2_macOS_arm64.tar.gz"
      sha256 "8fa37b50b8b21cd0b817ce4b443306cf142fa5e227f86af112b3511eb3cd78b0"

      def install
        bin.install "dpx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpx/dpx/releases/download/v0.1.2/dpx_0.1.2_macOS_x86_64.tar.gz"
      sha256 "dbd8f3b4ee55c30ba796031cb01e7939e23b7af37bc5a09ec6197f41fa85c0e0"

      def install
        bin.install "dpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dpx/dpx/releases/download/v0.1.2/dpx_0.1.2_linux_armv6.tar.gz"
      sha256 "35d214dcd09a3f40331818995a1992b03e156e7789a287f16e67f8d27d1d4fd9"

      def install
        bin.install "dpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpx/dpx/releases/download/v0.1.2/dpx_0.1.2_linux_arm64.tar.gz"
      sha256 "121945d817f197813aac501b3d6b643f95a0021964d5845d70015f97d2e5293d"

      def install
        bin.install "dpx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dpx/dpx/releases/download/v0.1.2/dpx_0.1.2_linux_x86_64.tar.gz"
      sha256 "6b1855fb624cf57a23a01f20067db37d08fc9afa1c9505268e0b45c3b04b854d"

      def install
        bin.install "dpx"
      end
    end
  end
end
