# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dpx < Formula
  desc "Run any executable inside container on your machine"
  homepage "https://github.com/dpx/dpx"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dpx/dpx/releases/download/v0.1.1/dpx_0.1.1_macOS_x86_64.tar.gz"
    sha256 "5b08d557c72977021f42b5bbea54c7fefa1c346f11b83e733318cf337beb5959"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dpx/dpx/releases/download/v0.1.1/dpx_0.1.1_macOS_arm64.tar.gz"
    sha256 "66e734534dd5592c9e4c40d7999518502eb228860c504e50667337f0cdd7a77d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dpx/dpx/releases/download/v0.1.1/dpx_0.1.1_linux_x86_64.tar.gz"
    sha256 "d9e83769ead0716bb02f773de094fd874cf69b51c7ab5fdeb8f0ed203f6a152e"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dpx/dpx/releases/download/v0.1.1/dpx_0.1.1_linux_armv6.tar.gz"
    sha256 "f86f27f87f7c08dc3956e1626d6041a03072678309692572f9bb14492f061dd4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dpx/dpx/releases/download/v0.1.1/dpx_0.1.1_linux_arm64.tar.gz"
    sha256 "4e6e215d93a89468120cee458cd71ca5784a661ab9c04c0adb02384b26feb223"
  end

  def install
    bin.install "dpx"
  end
end
